kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeployments
spec:
   replicas: 1
   selector:     
    matchLabels:
     name: deployment
   template:
     metadata:
       name: javaapp
       labels:
         name: javaapp
     spec:
      containers:
        - name: javaapp
          image: manashwi/javaapp:tagVersion
          ports:
            - containerPort: 8080
