apiVersion: v1
kind: Pod
metadata:
  name: javapod
  labels:
    app: javapod
spec:
  containers:
    - name: javaapp
      image: manashwi/javaapp:tagVersion
      ports:
        - containerPort: 8080
